const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const {build,load,serve}=require('../skills/visual-review/scripts/review.cjs');
const schema=require('../skills/visual-review/assets/schema.js');
function fixture(t){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'visual-review-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.mkdirSync(path.join(root,'media'));
  fs.writeFileSync(path.join(root,'media/after.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5V0AAAAASUVORK5CYII=','base64'));
  const m={schema_version:1,capture_id:'test-round-1',title:'Button label',repository:'example/app',pr:1,head_sha:'a'.repeat(40),base_sha:'b'.repeat(40),captured_at:'2026-09-04T12:00:00Z',summary:'Rename the button',coverage_notes:'Single button fixture',changed_files:['button.html'],assets:[{id:'after',path:'media/after.png',kind:'after',label:'Button',observed:'One pixel fixture, not product evidence',inspected:true,width:1,height:1,source:{commit:'a'.repeat(40),url:'http://127.0.0.1:1234/',provenance:'test fixture',state:'default',role:'test',theme:'light',conditions:'fixed fixture',viewport:{width:1280,height:800}}}],changes:[{id:'button',title:'Button',description:'Rename',files:['button.html'],status:'captured',asset_ids:['after']}]};
  const input=path.join(root,'manifest.json');const write=()=>fs.writeFileSync(input,JSON.stringify(m));write();return{root,m,input,write};
}
function feedback(m){return{schema_version:1,repository:m.repository,pr:m.pr,capture_id:m.capture_id,head_sha:m.head_sha,authenticated:false,author:'PM',exported_at:'2026-09-04T12:00:00Z',recommendation:'draft',annotations:[{id:'a-1',change_id:'button',asset_id:'after',kind:'pin',text:'Change this',created_at:'2026-09-04T12:00:00Z',x:.5,y:.5}]};}
test('each asset requires a capture-bound approval before overall recommendation',t=>{const {m}=fixture(t),f=feedback(m);f.recommendation='recommend-approval';assert.throws(()=>schema.feedback(f,m),/needs approval/);f.asset_approvals=[{asset_id:'after',author:'PM',approved_at:f.exported_at}];assert.equal(schema.feedback(f,m),f);f.asset_approvals[0].asset_id='other';assert.throws(()=>schema.feedback(f,m),/Unknown approved asset/);});
test('markup geometry and styles validate without modifying image evidence',t=>{
  const {m}=fixture(t),f=feedback(m),a=f.annotations[0];
  Object.assign(a,{kind:'arrow',end_x:.8,end_y:.8,color:'#e25a30',stroke_width:4});assert.equal(schema.feedback(f,m),f);
  a.end_x=2;assert.throws(()=>schema.feedback(f,m),/arrow end x/);a.end_x=.8;
  a.kind='pen';a.points=[{x:.5,y:.5},{x:.8,y:.8}];assert.equal(schema.feedback(f,m),f);
  a.points[1].y=-1;assert.throws(()=>schema.feedback(f,m),/pen y/);a.points[1].y=.8;
  a.color='url(bad)';assert.throws(()=>schema.feedback(f,m),/color/);a.color='#e25a30';
  a.kind='ellipse';a.width=.7;a.height=.2;assert.throws(()=>schema.feedback(f,m),/outside image/);
});
test('build creates portable package with content hashes and refuses overwrite',t=>{const f=fixture(t),out=path.join(f.root,'report');build(f.input,out);const m=load(path.join(out,'manifest.json'));assert.match(m.assets[0].sha256,/^[a-f0-9]{64}$/);assert.ok(fs.existsSync(path.join(out,'index.html')));assert.throws(()=>build(f.input,out),/already exists/);fs.appendFileSync(path.join(out,'media/after.png'),'changed');assert.throws(()=>load(path.join(out,'manifest.json')),/digest/);});
test('unmapped files, missing assets and uninspected evidence cannot be captured',t=>{const f=fixture(t);f.m.changed_files.push('other.css');assert.throws(()=>schema.manifest(f.m),/missing from inventory/);f.m.changed_files.pop();f.m.changes[0].asset_ids=['absent'];assert.throws(()=>schema.manifest(f.m),/Unknown asset/);f.m.changes[0].asset_ids=['after'];f.m.assets[0].inspected=false;assert.throws(()=>schema.manifest(f.m),/inspected/);});
test('every asset must be exposed by at least one change',t=>{const{m}=fixture(t);m.assets.push({...m.assets[0],id:'orphan',path:'media/orphan.png'});assert.throws(()=>schema.manifest(m),/Asset missing from change inventory/);m.changes[0].asset_ids.push('orphan');assert.equal(schema.manifest(m),m);});
test('blocked evidence produces a valid incomplete package but cannot recommend approval',t=>{const f=fixture(t);Object.assign(f.m.changes[0],{status:'blocked',reason:'Auth fixture unavailable',asset_ids:[]});f.m.assets=[];f.write();build(f.input,path.join(f.root,'report'));const x=feedback(f.m);x.annotations=[];x.recommendation='recommend-approval';assert.throws(()=>schema.feedback(x,f.m),/Incomplete/);});
test('feedback must match repository, PR, head, capture and exact asset/change mapping',t=>{const{m}=fixture(t);for(const key of ['repository','capture_id','head_sha','pr']){const f=feedback(m);f[key]='other';assert.throws(()=>schema.feedback(f,m),/belong/);}const f=feedback(m);f.annotations[0].asset_id='missing';assert.throws(()=>schema.feedback(f,m),/Unknown asset/);});
test('coordinates, duplicate IDs, timestamps and local authority are checked',t=>{const{m}=fixture(t);const f=feedback(m);f.annotations[0].x=1.1;assert.throws(()=>schema.feedback(f,m),/invalid number/);f.annotations[0].x=.5;f.annotations.push({...f.annotations[0]});assert.throws(()=>schema.feedback(f,m),/duplicate/);f.annotations.pop();f.authenticated=true;assert.throws(()=>schema.feedback(f,m),/unauthenticated/);f.authenticated=false;f.annotations[0].kind='timestamp';assert.throws(()=>schema.feedback(f,m),/requires video/);});
test('video timestamp and cropped-image reference bounds',t=>{const{m}=fixture(t);m.assets.push({...m.assets[0],id:'video',kind:'video',path:'media/demo.webm',duration:2});m.changes[0].asset_ids.push('video');const f=feedback(m);Object.assign(f.annotations[0],{asset_id:'video',kind:'timestamp',time:1.5});assert.equal(schema.feedback(f,m),f);f.annotations[0].time=3;assert.throws(()=>schema.feedback(f,m),/timestamp/);m.assets.push({...m.assets[0],id:'crop',path:'media/crop.png',kind:'detail',parent_id:'after',crop:{x:0,y:0,width:2,height:1}});assert.throws(()=>schema.manifest(m),/crop width/);});
test('rework responses require every original annotation and current evidence',t=>{const{m}=fixture(t);const f=feedback(m);const r={schema_version:1,capture_id:m.capture_id,feedback_capture_id:f.capture_id,items:[]};assert.throws(()=>schema.responses(r,f,m),/missing a response/);r.items.push({annotation_id:'a-1',status:'addressed',explanation:'Test response',asset_ids:[]});assert.throws(()=>schema.responses(r,f,m),/current-result evidence/);r.items[0].asset_ids=['after'];assert.equal(schema.responses(r,f,m),r);});
test('every addressed response asset must be inspected current-result evidence',t=>{const{m}=fixture(t);const f=feedback(m),item={annotation_id:'a-1',status:'addressed',explanation:'Test response',asset_ids:['after']},r={schema_version:1,capture_id:m.capture_id,feedback_capture_id:f.capture_id,items:[item]};m.assets[0].kind='before';m.assets[0].source.commit=m.base_sha;assert.throws(()=>schema.responses(r,f,m),/current-result/);item.status='unresolved';assert.equal(schema.responses(r,f,m),r);item.status='addressed';m.assets[0].kind='after';assert.throws(()=>schema.responses(r,f,m),/current-result/);m.assets[0].source.commit=m.head_sha;m.assets[0].inspected=false;assert.throws(()=>schema.responses(r,f,m),/current-result/);m.assets[0].inspected=true;m.assets.push({...m.assets[0],id:'before',kind:'before',path:'media/before.png',source:{...m.assets[0].source,commit:m.base_sha}});m.changes[0].asset_ids.push('before');item.asset_ids.push('before');assert.throws(()=>schema.responses(r,f,m),/current-result/);item.asset_ids=['after'];for(const kind of ['after','detail','video']){m.assets[0].kind=kind;assert.equal(schema.responses(r,f,m),r);}});
test('documented build, feedback and rework recipes execute under bash and zsh',t=>{
  const skillRoot=path.resolve(__dirname,'../skills/visual-review');
  const blocks=[...fs.readFileSync(path.join(skillRoot,'SKILL.md'),'utf8').matchAll(/```bash\n([\s\S]*?)\n```/g)].map(m=>m[1]);
  for(const shell of ['bash','zsh']){
    const x=fixture(t),out=path.join(x.root,'original'),env={...process.env,VISUAL_REVIEW_ROOT:skillRoot,VISUAL_REVIEW_MANIFEST:x.input,VISUAL_REVIEW_OUTPUT:out};
    const run=block=>{const r=spawnSync(shell,['-c',block],{env,encoding:'utf8',timeout:30000});assert.equal(r.status,0,r.stderr||r.error?.message);};
    run(blocks[0]);env.VISUAL_REVIEW_ORIGINAL_MANIFEST=path.join(out,'manifest.json');
    env.VISUAL_REVIEW_FEEDBACK=path.join(x.root,'feedback.json');const f=feedback(x.m);fs.writeFileSync(env.VISUAL_REVIEW_FEEDBACK,JSON.stringify(f));run(blocks[2]);
    x.m.capture_id='round-2';x.write();env.VISUAL_REVIEW_OUTPUT=path.join(x.root,'rework');env.VISUAL_REVIEW_RESPONSES=path.join(x.root,'responses.json');
    fs.writeFileSync(env.VISUAL_REVIEW_RESPONSES,JSON.stringify({schema_version:1,capture_id:'round-2',feedback_capture_id:f.capture_id,items:[{annotation_id:'a-1',status:'addressed',explanation:'Test evidence',asset_ids:['after']}]}));run(blocks[3]);
  }
});
test('media cannot escape source through paths or symlinks',t=>{const f=fixture(t);f.m.assets[0].path='media/../../secret.png';assert.throws(()=>schema.manifest(f.m),/safe relative/);f.m.assets[0].path='media/link.png';fs.symlinkSync(__filename,path.join(f.root,'media/link.png'));f.write();assert.throws(()=>load(f.input),/escapes/);});
test('head provenance, media magic and dimensions are verified',t=>{const f=fixture(t);f.m.assets[0].source.commit=f.m.base_sha;assert.throws(()=>schema.manifest(f.m),/match head/);f.m.assets[0].source.commit=f.m.head_sha;f.m.assets[0].width=2;f.write();assert.throws(()=>load(f.input),/dimensions/);f.m.assets[0].width=1;f.write();fs.writeFileSync(path.join(f.root,'media/after.png'),'<script>bad()</script>');assert.throws(()=>load(f.input),/signature/);});
test('uppercase media extensions validate and serve with the matching content type',async t=>{const f=fixture(t);fs.renameSync(path.join(f.root,'media/after.png'),path.join(f.root,'media/after.PNG'));f.m.assets[0].path='media/after.PNG';f.write();const out=path.join(f.root,'report');build(f.input,out);const server=serve(out);await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const response=await fetch(`http://127.0.0.1:${server.address().port}/media/after.PNG`);assert.equal(response.status,200);assert.equal(response.headers.get('content-type'),'image/png');});
test('server binds loopback, serves media ranges, excludes unrelated files and writes',async t=>{const f=fixture(t),out=path.join(f.root,'report');build(f.input,out);fs.writeFileSync(path.join(out,'secret.txt'),'secret');const server=serve(out);await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${server.address().port}`;assert.equal((await fetch(base)).status,200);assert.equal((await fetch(base+'/secret.txt')).status,404);assert.equal((await fetch(base,{method:'POST'})).status,405);const r=await fetch(base+'/media/after.png',{headers:{Range:'bytes=0-7'}});assert.equal(r.status,206);assert.equal((await r.arrayBuffer()).byteLength,8);});
